spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shapyfy
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shapyfy
    user: postgres
    password: postgres