spring:
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration
  datasource:
    url: jdbc:postgresql://psql01.mikr.us:5432/db_adrian247
    username: adrian247
    password: 93C4_1daf1e
