spring:
  application:
    name: core
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration
  datasource:
    url: jdbc:postgresql://psql01.mikr.us:5432/db_adrian247?schema=shapyfy
    username: adrian247
    password: 93C4_1daf1e

anthropic:
  api-key: ${ANTHROPIC_API_KEY:}

