spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shapyfy
    username: shapyfy
    password: shapyfy
  jpa:
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shapyfy
    user: shapyfy
    password: shapyfy