spring:
  datasource:
    url: jdbc:postgresql://shapyfy-dev.ced9itxhrlae.eu-central-1.rds.amazonaws.com:5432/postgres?currentSchema=shapyfy
    username: postgres
    password: 3SKL2acKcUrNN52v43tZ
  jpa:
    show-sql: true
  flyway:
    url: jdbc:postgresql://shapyfy-dev.ced9itxhrlae.eu-central-1.rds.amazonaws.com:5432/postgres?currentSchema=shapyfy
    user: postgres
    password: 3SKL2acKcUrNN52v43tZ