global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'shapyfy-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'shapyfy-core'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['shapyfy-core:8080']
        labels:
          application: 'shapyfy-core'
          environment: 'production'
