INSERT INTO exercises(name)
VALUES ('Wyciskanie sztangi na ławce płaskiej'),
       ('Wyciskanie sztangi skos dodatni'),
       ('Rozpiętki na bramie wyciąg górny'),
       ('Wyciskanie żołnierskie'),
       ('Wznosy bokiem hantlami'),
       ('Wyciskanie francuskie hantlami'),
       ('Wiosłowanie sztangą'),
       ('Ściąganie drążka wąski chwyt'),
       ('Facepull'),
       ('Biceps gryf łamany'),
       ('Hantle z supinacją'),
       ('Przysiad'),
       ('Czwórki na maszynie'),
       ('Dwójki na maszynie'),
       ('Łydki na maszynie'),
       ('Wyciskanie hantli na ławce płaskiej'),
       ('Wyciskanie hantli skos dodatni'),
       ('Rozpiętki na bramie wyciąg dolny'),
       ('Wznosy bokiem na wyciągu'),
       ('Pompki na poręczach'),
       ('Triceps warkocze'),
       ('Wiosłowanie hantlami skos 45'),
       ('Ściąganie chwytu wyciągu górnego jednorącz'),
       ('Narciarz'),
       ('Zginanie przedramion w oparciu na ławce 75'),
       ('Uginanie ramion w opadzie na ławce 45'),
       ('Martwy ciąg'),
       ('Bułgary'),
       ('Zginanie nóg z gumą'),
       ('Łydki na smithie'),
       ('Łydki z hantlami na stepie')
;
